var fs=require('fs');
// 模块5: 详情弹窗 (showPinDetail + close + save + images + comments + delete)
var code = [
  "function showPinDetail(idx){curPinIdx=idx;var p=pins[idx];var ic=getIconUrl(p.name);var title=document.getElementById('pdTitle');if(title){title.innerHTML='';if(ic){var img=document.createElement('img');img.src=ic;img.style.cssText='width:28px;height:28px;border-radius:4px;object-fit:cover;vertical-align:middle;margin-right:6px';title.appendChild(img);}title.appendChild(document.createTextNode(' '+(p.name||p.type||'?')));}var pc=document.getElementById('pdCoord');if(pc)pc.textContent=Math.round(p.x)+'%, '+Math.round(p.y)+'%';var note=document.getElementById('pdNote');if(note)note.value=p.note||'';renderPinComments();renderPinImages();var pd=document.getElementById('pd');if(pd)pd.classList.add('show');}",
  "function closePinDetail(){document.getElementById('pd').classList.remove('show');curPinIdx=null;}",
  "function savePinNote(){if(curPinIdx===null)return;var note=document.getElementById('pdNote');if(!note)return;pins[curPinIdx].note=note.value;localStorage.setItem('abi_'+mapNameEng+'_pins',JSON.stringify({pins:pins,mapComments:mapComments}));var saved=document.getElementById('pdSaved');if(saved){saved.textContent='OK';setTimeout(function(){saved.textContent='';},2000);}}",
  "function renderPinImages(){var grid=document.getElementById('pdImgGrid');if(!grid)return;grid.innerHTML='';if(curPinIdx===null)return;var imgs=pins[curPinIdx].images||[];imgs.forEach(function(src,i){var img=document.createElement('div');img.style.cssText='width:60px;height:60px;background-size:cover;background-image:url('+src+');border-radius:4px;border:1px solid #333;cursor:pointer;position:relative';img.onclick=function(){if(confirm('Delete?')){pins[curPinIdx].images.splice(i,1);localStorage.setItem('abi_'+mapNameEng+'_pins',JSON.stringify({pins:pins,mapComments:mapComments}));renderPinImages();}};grid.appendChild(img);});}",
  "function addPinImages(files){if(!files||!files.length||curPinIdx===null)return;Array.from(files).forEach(function(file){var reader=new FileReader();reader.onload=function(e){if(!pins[curPinIdx].images)pins[curPinIdx].images=[];pins[curPinIdx].images.push(e.target.result);localStorage.setItem('abi_'+mapNameEng+'_pins',JSON.stringify({pins:pins,mapComments:mapComments}));renderPinImages();};reader.readAsDataURL(file);});}",
  "function deleteCurrentPin(){if(!localStorage.getItem('abi_token')){loginGitHub();return;}if(curPinIdx===null)return;var p=pins[curPinIdx];if(!confirm('\\u786e\\u5b9a\\u5220\\u9664\\u8be5\\u5bb9\\u5668?'))return;var ustr=localStorage.getItem('abi_user');var uname='Anon';try{var uj=JSON.parse(ustr);uname=uj.user_metadata&&uj.user_metadata.preferred_username||uj.user_metadata&&uj.user_metadata.user_name||'Anon';}catch(e){}if(p.id){var x=p.x,y=p.y;supabase('deletion_requests','POST',{pin_id:p.id,name:p.name,x:x,y:y,submitted_by:uname,type:p.type||'',ic:p.ic||''}).then(function(){alert('\\u5df2\\u63d0\\u4ea4\\u5220\\u9664\\u5ba1\\u6838');pins.splice(curPinIdx,1);localStorage.setItem('abi_'+mapNameEng+'_pins',JSON.stringify({pins:pins,mapComments:mapComments}));closePinDetail();renderMarkers();var ov=document.createElement('div');ov.style.cssText='position:fixed;bottom:20px;left:50%;transform:translateX(-50%);background:#1a1a2e;border:1px solid #ff4444;border-radius:10px;padding:12px 20px;z-index:99999;max-width:90vw;text-align:center';var u=window.location.origin+window.location.pathname.replace(/\\/[^\\/]+$/,'/map-farm.html')+'?x='+x+'&y='+y;ov.innerHTML='<div style=\"color:#ff4444;font-size:14px;font-weight:600;margin-bottom:8px\">\\u5df2\\u63d0\\u4ea4\\u5220\\u9664\\u5ba1\\u6838</div><div style=\"color:#888;font-size:12px;margin-bottom:10px\">\\u7b49\\u5f85\\u7ba1\\u7406\\u5458\\u5ba1\\u6838\\u540e\\u5c06\\u79fb\\u9664</div><a href=\"'+u+'\" style=\"color:#88aaff;font-size:13px;text-decoration:underline\">\\ud83d\\udccd \\u5728\\u5730\\u56fe\\u4e0a\\u67e5\\u770b\\u4f4d\\u7f6e</a><br><button onclick=\"this.parentElement.remove()\" style=\"margin-top:10px;padding:4px 16px;background:#333;border:none;border-radius:6px;color:#888;cursor:pointer\">\\u5173\\u95ed</button>';document.body.appendChild(ov);})['catch'](function(e){alert('Err: '+e.message);});}else{pins.splice(curPinIdx,1);localStorage.setItem('abi_'+mapNameEng+'_pins',JSON.stringify({pins:pins,mapComments:mapComments}));closePinDetail();renderMarkers();alert('\\u5df2\\u5220\\u9664');}}",
  "function renderPinComments(){var list=document.getElementById('pdcList');list.innerHTML='';if(curPinIdx===null)return;(pins[curPinIdx].comments||[]).forEach(function(c){var item=document.createElement('div');item.style.cssText='padding:8px;border-bottom:1px solid #222;font-size:13px';var time=document.createElement('span');time.style.cssText='color:#666;font-size:11px';time.textContent=c.time||'';var txt=document.createElement('div');txt.style.cssText='margin-top:4px';txt.textContent=c.text||'';item.appendChild(time);item.appendChild(txt);list.appendChild(item);});}",
  "function renderMapComments(){var list=document.getElementById('mcList');list.innerHTML='';mapComments.forEach(function(c){var item=document.createElement('div');item.style.cssText='padding:8px;border-bottom:1px solid #222;font-size:13px';var time=document.createElement('span');time.style.cssText='color:#666;font-size:11px';time.textContent=c.time||'';var txt=document.createElement('div');txt.style.cssText='margin-top:4px';txt.textContent=c.text||'';item.appendChild(time);item.appendChild(txt);list.appendChild(item);});}",
  "function showNextCommentInput(){var inp=document.getElementById('pdcInput');var btn=document.getElementById('pdcBtn');if(inp)inp.style.display='block';if(btn)btn.style.display='none';}",
  "function submitPinComment(){if(curPinIdx===null)return;var input=document.getElementById('pdcInput');var text=input.value.trim();if(!text)return;var comment={text:text,time:new Date().toLocaleString('zh-CN')};if(!pins[curPinIdx].comments)pins[curPinIdx].comments=[];pins[curPinIdx].comments.push(comment);localStorage.setItem('abi_'+mapNameEng+'_pins',JSON.stringify({pins:pins,mapComments:mapComments}));input.value='';renderPinComments();}",
  "function submitMapComment(){var input=document.getElementById('mcInput');var text=input.value.trim();if(!text)return;var comment={text:text,time:new Date().toLocaleString('zh-CN')};mapComments.push(comment);localStorage.setItem('abi_'+mapNameEng+'_pins',JSON.stringify({pins:pins,mapComments:mapComments}));input.value='';renderMapComments();}"
];

var full=code.join('\n');
var op=(full.match(/\(/g)||[]).length;
var cp=(full.match(/\)/g)||[]).length;
var ob=(full.match(/\{/g)||[]).length;
var cb=(full.match(/\}/g)||[]).length;
console.log('module5: ('+op+'='+cp+') {'+ob+'='+cb+'} '+(op===cp&&ob===cb?'OK':'FAIL'));
if(op!==cp||ob!==cb){console.log('FAIL - abort');process.exit(1);}

var maps=['map-farm','map-beishan','map-valley','map-armory','map-airport','map-tvstation'];
maps.forEach(function(m){
  var fp='F:\\暗区突围网站\\pages\\'+m+'.html';
  var c=fs.readFileSync(fp,'utf8');
  c=c.replace('</script>', full+'\n</script>');
  fs.writeFileSync(fp,c);
  console.log(m+': OK');
});
console.log('module5 DONE');
