# Let me check what the actual error is
# The "permission denied" could mean:
# 1. No INSERT permission on post_comments for authenticated role (despite RLS policy)
# 2. Sequence permission denied for GENERATED AS IDENTITY
# 3. Schema permission issue

# The GENERATED ALWAYS AS IDENTITY column needs sequence USAGE on the implicit sequence
# Solution: 
# 1. Grant sequence usage
# 2. OR change to GENERATED BY DEFAULT AS IDENTITY
# 3. OR use serial type instead

sql = """
-- Drop and recreate without identity (simpler, no sequence issues)
DROP TABLE IF EXISTS post_comments CASCADE;

CREATE TABLE post_comments (
  id serial PRIMARY KEY,
  post_id integer REFERENCES map_posts(id) ON DELETE CASCADE,
  author text NOT NULL,
  content text NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE post_comments ENABLE ROW LEVEL SECURITY;

-- Simple policies
CREATE POLICY "认证用户可评论" ON post_comments FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "所有人可看评论" ON post_comments FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "自己可删评论" ON post_comments FOR DELETE TO authenticated USING (author = (auth.jwt() ->> 'preferred_username'));

-- Grant perms
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON post_comments TO authenticated;
GRANT ALL ON post_comments_id_seq TO authenticated;
GRANT SELECT ON post_comments TO anon;
"""
print(sql)
